//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { GroupMemberMatchType } from "@Obsidian/Enums/Blocks/Group/Scheduling/groupMemberMatchType";
import { ResourceListSourceType } from "@Obsidian/Enums/Blocks/Group/Scheduling/resourceListSourceType";

/** The resource settings to indicate how individuals should be selected for assignment. */
export type GroupSchedulerResourceSettingsBag = {
    /** Gets or sets the enabled Rock.Enums.Blocks.Group.Scheduling.ResourceListSourceTypes, from which individuals may be scheduled. */
    enabledResourceListSourceTypes?: ResourceListSourceType[] | null;

    /** Gets or sets the selected Rock.Enums.Blocks.Group.Scheduling.GroupMemberMatchType. */
    matchType: GroupMemberMatchType;

    /** Gets or sets the selected Rock.Enums.Blocks.Group.Scheduling.ResourceListSourceType. */
    sourceType: ResourceListSourceType;
};
