//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

/** The group member match type options available in the Group Scheduler block. */
export const GroupMemberMatchType = {
    /** Show all members of the selected group. */
    AllGroupMembers: 0,

    /** Show all members of the selected group that have a scheduling preference set for the selected week. */
    MatchingWeek: 1,

    /** Show all members of the selected group that have a scheduling preference set for the selected week AND whose assignment (location/schedule) matches the selected location and schedule OR they have no assignment. */
    MatchingAssignment: 2
} as const;

/** The group member match type options available in the Group Scheduler block. */
export const GroupMemberMatchTypeDescription: Record<number, string> = {
    0: "All Group Members",

    1: "Matching Week",

    2: "Matching Assignment"
};

/** The group member match type options available in the Group Scheduler block. */
export type GroupMemberMatchType = typeof GroupMemberMatchType[keyof typeof GroupMemberMatchType];
